module.exports.descriptors = [
    'Spacious',
    'Cozy',
    'Modern',
    'Elite',
    'Sophisticated',
    'Bright',
    'Welcoming',
    'Splendid',
    'opulent',
    'Serene',
    'Splendid ',
    'Organized',
    'Grandiose',
    'Comfortable',
    'Elegant',
    'Charming',
    'Sophisticated',
    'Luxurious',
    'Minimalistic',
    'Sumptuous'
]

module.exports.places = [
    'Family Home',
    'Apartment',
    'Townhouse',
    'Condo',
    'Studio',
    'Hotel Room',
    'Hotel Suit',
    'Bach House',
    'Beach Apartment',
    'Loft Apartment',
    'Lake House',
    'Forest Cabbana',
    'Hotel Executive Room',
    'Mansion',
    'Farmhouse',
    'Duplex',
    'Bungalow',
    'Hotel Junior Suite',
    'Hotel Presidential Suite',
    'Hotel Studio Room',
    'One Room Apartment',
    'Beach Apartment'
]